refactoring
Edge-Center/terraform-provider-edgecenter pull request #3
Opened 2023-01-27 10:44 UTC by anaxaim

- import sorting
- linters

2023-02-13 20:45 UTC, alex2304 requested changes
Great job!

And special thanks for splitting changes into different commits 🙏 

Please, do the remaining:
1. Remove known unused definitions, including those structs in `utils.go`.
2. Check that you do not change the json format (see `type Region struct` as an example)
3. Add to `README.md` how to run tests and how to specify env variables needed for running tests

2023-02-13 20:45 UTC, alex2304 commented on edgecenter/test/main_test.go
>  func regionInfo() string {
Снова потенциально не используемые места

Если есть ещё такие - предлагаю просто убрать, если правда не используется

2023-02-13 20:45 UTC, alex2304 commented on edgecenter/test/.env
> +EC_PASSWORD=XSW@2wsx
No new line at the end of the file

2023-02-13 20:45 UTC, alex2304 commented on edgecenter/test/.env
> +EC_CLOUD_API=https://api.preprod.be/cloud
`api.preprod.online`

2023-02-13 20:45 UTC, alex2304 commented on edgecenter/test/.env
> +EC_CLOUD_API=https://api.preprod.be/cloud
Эти энвы необходимы для запуска тестов? Каким образом энвы из этого файла нужно подгружать?

2023-02-13 20:45 UTC, alex2304 commented on edgecenter/test/.env
> +EC_USERNAME=evgeniy.michurin@edgecenter.ru
Давай использовать общий аккаунт для тестов (в закрепе в чате от него креды)

2023-02-13 20:45 UTC, alex2304 commented on edgecenter/utils.go
> +	DisplayName string `json:"displayName"`
Похоже, ты поменял название поля в json формате

Но эта структура нигде не используется, судя по usage


<img width="378" alt="image" src="https://user-images.githubusercontent.com/7988418/218569398-d7e0d237-fc40-44a3-8ddf-c33eac1422a6.png">

2023-02-14 06:00 UTC, anaxaim commented on edgecenter/utils.go
> +// nolint: unused
убрал аннотации `// nolint: unused` функции все используются теперь. проблема была в тегах

2023-02-14 06:02 UTC, anaxaim commented on edgecenter/test/utils_test.go
>  func TestExtractHosAndPath(t *testing.T) {
поправил

2023-02-14 06:10 UTC, anaxaim commented on edgecenter/test/utils_test.go
> +			t.Parallel()
конкрутеного доступа не будет, под капотом мьютексы в доп функции waitParallel

а на счет чувствительного сервиса, параллельность включено для cdn, dns и storage. я поставлю себе задачу на отслеживание в динамике этого момента, когда тесты будут ходит. последним с месяц, увеличивается ли время прохождения. потому что сейчас нельзя сказать с точностью, как влияет. параллельность - это рекомендация линтера

2023-02-14 06:10 UTC, anaxaim commented on edgecenter/test/main_test.go
>  func regionInfo() string {
+

2023-02-14 06:11 UTC, anaxaim commented on edgecenter/test/.env
> +EC_CLOUD_API=https://api.preprod.be/cloud
этого файла не будет, случайно закинул. энвы будут генериться в gitlabci автоматически. этот файл удобно использовать локально при запуске тестов

2023-02-14 06:11 UTC, anaxaim commented on edgecenter/test/.env
> +EC_USERNAME=evgeniy.michurin@edgecenter.ru
ок

2023-02-14 06:15 UTC, anaxaim commented on edgecenter/utils.go
> +	DisplayName string `json:"displayName"`
выпилил все неиспользуемые из этого файла

2023-02-14 06:16 UTC, anaxaim commented on edgecenter/test/.env
> +EC_PASSWORD=XSW@2wsx
+. файл или уберу или оставлю только энвы, которые надо будет заполнить при локальном запуске тестов

2023-02-14 06:34 UTC, anaxaim commented on edgecenter/test/utils_test.go
> +		tt := tt
вот тут хороший пример с объяснением ["Изменяемость for-range"](https://medium.com/nuances-of-programming/из-опыта-работы-с-golang-путь-проб-и-ошибок-cc662ec36d73), 

в примере по ссылке на вход анонимной функции передается переменная. мы же используем замыкание, и тоже каждый раз перехватываем переменную, а не копируем ее

2023-02-17 21:06 UTC, alex2304 approved these changes

2023-02-19 07:12 UTC, merged