feat(CLOUDDEV-420): added disable_port_security option to instance re…
Edge-Center/terraform-provider-edgecenter pull request #38
Opened 2023-12-26 10:50 UTC by DamirZinatullin

…source

2023-12-26 12:27 UTC, ipaqsa approved these changes

2024-01-09 15:40 UTC, alex2304 requested changes

2024-01-09 15:40 UTC, alex2304 commented on docs/resources/cdn_sslcert.md
> -
Старайся делать изменения в форматировании отдельно от бизнес-логики, потому что иначе не удобно смотреть MR: много лишних файлов в списке изменений и приходится фильтровать нужные

Если все-таки необходимо сделать в одном PRе, выноси форматирование в отдельный коммит, когда это возможно

2024-01-09 15:40 UTC, alex2304 commented on edgecenter/utils_instance.go
> +	interfacesListAPI, err := instances.ListInterfacesAll(instanceClient, instanceID)
Когда функция большая и состоит из нескольких этапов, можно выделить явные шаги. Например, выше у тебя происходил attach интерфейса, а ниже приведение поля disable_port_security в соответствии с его значением в opts. 

Я обычно подписываю такие шаги, чтобы легче было читать код. 

Предлагаю тебе еще раз взглянуть на твой код и посмотреть, будет ли здесь актуально тоже подписать, что это за большой шаг внутри функции

2024-01-09 15:40 UTC, alex2304 commented on edgecenter/utils_instance.go
> +	interfacesListAPI, err := instances.ListInterfacesAll(instanceClient, instanceID)
Долго читал функцию, особенно меня смутило, почему у тебя в цикле проверяется opts, если opts -- это объект, сформированный только для запроса выше в функции.

Это наглядный пример, почему стоит когда это возможно следить за тем, чтобы функция выполняла ровно одну задачу. Иначе нужно внимательно следить, чтобы переменные, предназначеные для чего-то одного, не использовались там, где они не предназначена.

2024-01-09 15:40 UTC, alex2304 commented on edgecenter/resource_edgecenter_instance.go
> +			for _, interfaceExtracted := range portSecurityOptsListExtracted {
Здесь явно путаница в типах, отмечу те проблемы, которые заметил:
1. Из того, что я заметил, всё что `opts` обозначает параметры для запросов к Cloud API. У тебя `InstancePortSecurityOpts` кажется не используется в таком ключе, обозначает что-то другое.
2. В этой функции непонятно чем отличается `portSecurityOptsList` от `portSecurityOptsListExtracted`: они имеют одинаковый тип, и первый собирается из второго. Это мешает разобраться, что делает код.
3. И третье - в строке `for _, interfaceExtracted := range portSecurityOptsListExtracted {` у тебя то, что было `opts`, превращается в `interface`, что окончательно вносит путаницу

Проверь, пожалуйста, и поправь, если действительно есть проблема здесь

2024-01-18 07:46 UTC, alex2304 commented
Стало проще и легче читать, аппрувнул

2024-01-18 07:47 UTC, alex2304 approved these changes

2024-01-18 12:38 UTC, merged